config/routes.rb
TestNew::Application.routes.draw do
  resources :announcements

  resources :artworks

  resources :collections

  match "ajax_gallery"  =>"artworks#ajax_gallery"

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
 attr_accessible :message, :starts_at, :ends_at

  def self.search(search)
    if search
      where('message LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

 # def self.current_announcements   #class method
  #with_scope :find => { }
    #if hide_time.nil?
     # find [:all, :conditions => (['starts_at <= ?', DateTime.now]&['ends_at >= ?', DateTime.now])]
  #  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # GET /announcements
  # GET /announcements.xml
    #before_filter :get_announcements, :except => [:show]
  def index
    @announcements = Announcement.search(params[:search]).order(params[:sort]).paginate(:per_page =>3, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully created.') }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end




end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcements.html.erb
<div id="announcements"><table>
  <tr>
    <th><%= link_to "Message", :sort => "message" %></th>
    <th><%= link_to "Starts at", :sort => "starts_at" %></th>
    <th><%= link_to "Ends at", :sort => "ends_at" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.message %></td>
        <td><%= announcement.starts_at %></td>
        <td><%= announcement.ends_at %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @announcements %>

</div>

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<!--<script src="/js/jquery-1.3.2.min.js" type="text/javascript"></script> -->
<h1>Listing announcements</h1>
<%= form_tag announcements_path, :method =>'get', :id => "announcements_search" do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<div id="announcements"><%= render 'announcements' %></div>

<br />

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/index.js.erb
$("#announcements").html("<%= escape_javascript(render("announcements"))%>")

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @announcement.message %>
</p>

<p>
  <b>Starts at:</b>
  <%= @announcement.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @announcement.ends_at %>
</p>


<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>