config/routes.rb
TestNew::Application.routes.draw do
  resources :announcements

  resources :artworks

  resources :collections

  match "ajax_gallery"  =>"artworks#ajax_gallery"

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base

  attr_accessible :art_title, :image_url, :comment, :collection_id
  belongs_to :collection

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  # GET /artworks
  # GET /artworks.xml
  def index
    @artworks = Artwork.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artworks }
    end
  end

  def ajax_gallery
    render 'slideshow'
  end

  # GET /artworks/1
  # GET /artworks/1.xml
  def show
    @artwork = Artwork.find(params[:id])
    @collection = Collection.find ((@artwork.collection_id))

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artwork }
    end
  end

  # GET /artworks/new
  # GET /artworks/new.xml
  def new
    @artwork = Artwork.new
    @collections = Collection.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @artwork }
    end
  end

  # GET /artworks/1/edit
  def edit
    @artwork = Artwork.find(params[:id])

  end

  # POST /artworks
  # POST /artworks.xml
  def create
    @artwork = Artwork.new(params[:artwork])

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to(@artwork, :notice => 'Artwork was successfully created.') }
        format.xml  { render :xml => @artwork, :status => :created, :location => @artwork }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /artworks/1
  # PUT /artworks/1.xml
  def update
    @artwork = Artwork.find(params[:id])

    respond_to do |format|
      if @artwork.update_attributes(params[:artwork])
        format.html { redirect_to(@artwork, :notice => 'Artwork was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.xml
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy

    respond_to do |format|
      format.html { redirect_to(artworks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_form.html.erb
<%= form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for [@collection, @artwork] do |f| %>
        <%= f.label :art_title %><br />
            <%= f.text_field :art_title %>
          </div>
          <div class="field">
            <%= f.label :image_url %><br />
            <%= f.text_field :image_url %>
          </div>
          <div class="field">
            <%= f.label :comment %><br />
            <%= f.text_field :comment %>
          </div>
          <div class="actions">
            <%= f.submit %>
<% end %>
<%end %>

app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form' %>
<%# form_for(@artwork) do |j| %>
    <%# j.collection_select(:collection_id, @collections, :id, :collection_title, {:include_blank =>true}) -%>
    <%# end %>
<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>my blog</title>
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">
	<div id="header" class="container">
		<div id="logo">
         <img border="0" src="/images/img_head.png" alt="Pulpit rock" width="1000" height="300" />  </div>
			<h1><a href="http://localhost:3000/collections/"> <strong><small>The artist in me&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;</small></strong></a></h1>
			    <p>designs by <a href="http://www.surbhidangi.co.nr/">Surbhi Dangi</a></p>
		</div>
        <div id="menu">
			<ul>
				<li class="current_page_item"><a href="http://localhost:3000/artworks/">Homepage</a></li>
				<li><a href="http://www.surbhidangi.co.nr">Blog</a></li>
				<li><a href="http://localhost:3000/ajax_gallery/">Photos</a></li>
                <li><a href="http://localhost:3000/ajax_gallery/">Events</a></li>
				<li><a href="http://www.surbhidangi.co.nr">Contact</a></li>
			</ul>
		</div>
	</div>
    <div id="page">
		<div id="content">
			<div class="post">
				<h2 class="title"><a href="https://www.facebook.com/myartistspage">Welcome to my gallery  </a></h2>
				<p class="meta"><span class="date">September 23, 2011</span><span class="posted">Posted by <a href="#">Someone</a></span></p>
				<div style="clear: both;">&nbsp;</div>
				<div class="entry">
					<p>Auguste Rodin, the most famous sculptor of his day, not only appealed to American collectors but also had a profound influence on American artists. This exhibition is the first to examine the scope of this influence on artists such as Malvina Hoffman, Edward Steichen, Georgia O'Keeffe and others.</p>
					<p>Through October 16, 2011
This exhibition of 80 illustrated title pages traces the development of the title page from the 16th to 19th centuries. Title page illustrations by such artists as Giovanni Battista Piranesi, Canaletto, Francisco Goya, William Morris, Odilon Redon, and Aubrey Beardsley are featured in this display. </p>
                  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="www.facebook.com/myartistspage" data-send="true" data-width="450" data-show-faces="false" data-font="trebuchet ms"></div>
</div>  </br> </br>
			</div>
			<div style="clear: both;">&nbsp;</div>
		</div>
		<!-- end #content -->
		<div id="sidebar">
			<ul>
				<li>
					<!--<div id="search" >
						<form method="get" action="#">
							<div>
								<input type="text" name="s" id="search-text" value="" />
								<input type="submit" id="search-submit" value="GO" />
							</div>
						</form>
					</div> -->
					<div style="clear: both;">&nbsp;</div>
				</li>
				<li>
                  <h2>Quick Links</h2>
					<h2><%= link_to "My gallery", :controller => 'artworks', :action => 'ajax_gallery' %></h2>
                    <h2><a href="http://localhost:3000/announcements">All Announcements</a></h2>
				</li>
              <li>
					<h2>Philosophy</h2>
					<p>Loves seeing the ordinary as something that can be extraordinary..</p>
				</li>

			</ul>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end #page -->
</div>
<div id="footer-content">
	<div id="footer-bg" class="container">
		<div id="column1">
			<h2>Welcome to my website</h2>
			<p>The California Art Club was established in 1909, by artists, patrons, and visionaries for the sole purpose of capturing the beauty of California’s landscapes in their paintings. The California Historical Society is the only Bay Area venue for this exhibition celebrating the one hundred year legacy of the California Art Club.</p>
		</div>
		<div id="column2">
			<h2>Portfolio</h2>
			<p>A Century of Landscapes. Presenting an exhibition of artwork by members of the California Art Club celebrating the club’s one hundred year legacy. The California Art Club was established in 1909, by artists, patrons and visionaries for the sole purpose of capturing the beauty of California’s landscapes in their paintings. </p>
		</div>
		<div id="column3">
			<h2>Recommended Links</h2>
			<ul>
				<li><a href="http://museum.stanford.edu/">Richard Serra: Sequence</a></li>
				<li><a href="http://www.californiahistoricalsociety.org/">Dutch and Flemish Masterworks</a></li>
				<li><a href="http://www.californiahistoricalsociety.org/">Selections from the California Art Club </a></li>
			</ul>
		</div>
	</div>
</div>
<!--<div id="footer">
	<p>Copyright (c) 2011 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div> -->
<!-- end #footer -->
</body>
</html>

app/views/artworks/new.html.erb
<h1>New artwork</h1>
 <%= form_for(@artwork) do |f| %>
    <div class="field">
    <%= f.label :art_title %><br />
    <%= f.text_field :art_title %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :collection_id %><br />
    <%= f.collection_select(:collection_id, @collections, :id, :collection_title, {:include_blank =>true}) %>
  </div><div class="actions">
    <%= f.submit %>
  </div><% end %>
<%#= render 'form' %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
`<p id="notice"><%= notice %></p>

<p>
  <b>Art title:</b>
  <%= @artwork.art_title %>
</p>

<p>
  <b>Collection:</b>
  <%= @artwork.collection_id %>
</p>

<p>
  <b>Image url:</b>
  <%= @artwork.image_url %>
</p>

<p>
  <b>Comment:</b>
  <%= @artwork.comment %>
</p>


<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/slideshow.html.erb
<html>
<!--<body>

<h2>Image 1</h2>
<img border="0" src="/images/1.jpg" alt="Pulpit rock" width="304" height="228" />

<h2>Image 1</h2>
<img border="0" src="/images/2.jpg" alt="Pulpit rock" width="304" height="228" />

<h2>Image 1</h2>
<img border="0" src="/images/3.jpg" alt="Pulpit rock" width="304" height="228" />

</body> -->

<head>
<style type="text/css">
a:link {color:#A72000;}    /* unvisited link */
a:visited {color:#0000FF;} /* visited link */
a:hover {color:#0033cc;}   /* mouse over link */
a:active {color:#0000FF;}  /* selected link */
h1 {text-align: center;
    text-transform: lowercase;}
h2 {text-align: center;
    text-transform: lowercase;}
div.img
  {
      margin:2px;
  border:1px solid #8E8E8E;
  height:300px;
  width:400px;
    display:-moz-box;
    -moz-box-orient:horizontal;
    -moz-box-pack:center;
    -moz-box-align:center;

    padding-left: 125px;
    padding-right: 125px;
    padding-bottom: 0px;
    align: center;
    text-align:center;
  }
div.img img
  {
  display:inline;
  margin:3px;
  border:1px solid #ffffff;
  }
div.img a:hover img
  {
  border:1px solid #0000ff;
  }
div.desc
  {
  text-align:center;
  font-weight:normal;
  width:120px;
  margin:2px;
  }
</style>
</head>
<body>

</br></br><h1>My Gallery</h1></br></br></br></br></br></br>



  <!--<a target="_blank" href="klematis_big.htm"> -->
  <%# if (@artworks.image_url == "/images/child.jpg") %>
  <%# @artworks.image_url %>
  <% @artworks = Artwork.all %>
   <% @artworks.each do |art|   %>
   <div class="img"><img border="0" src=<%= art.image_url %> width="310" height="228" /></br>
   <div class="desc"><%= art.comment %></div></div>



        <%#</div>
      %>
   <!--
  <img border="0" src="/images/child.jpg" width="310" height="228" />
  <div class="desc"><%#<%= art.comment %></div>
      <%# end %>
</div>

<div class="img">
  <img border="0" src="/images/beach.jpg" width="330" height="250" />
  <div class="desc">Add a description of the image here</div>
</div>
<div class="img">
  <img border="0" src="/images/baby.jpg" width="243" height="180" />
  <div class="desc">Add a description of the image here</div>
</div>
<div class="img">
  <img border="0" src="/images/lion.jpg" width="340" height="228" />
  <div class="desc">Add a description of the image here</div>
</div>      -->
<% end %>


</br></br><h2><a href="http://localhost:3000/artworks/">Home</a></h2></br></br>

</body>
</html>